//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlovakAnalyzer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SlovakAnalyzer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sk_SK_aff {
            get {
                object obj = ResourceManager.GetObject("sk_SK_aff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 264944
        ///a
        ///A
        ///á
        ///Á
        ///à
        ///ä
        ///AB
        ///abája/U
        ///abak
        ///abaka
        ///abakteriálny/YN
        ///abakus
        ///Abakus
        ///abandon
        ///abandonovať
        ///abatiša/U
        ///abaton
        ///abaxiálny/YN
        ///abázia
        ///aba/zZ
        ///abažúr
        ///abbé/c
        ///ABC
        ///abcoulomb/B
        ///abd/C
        ///Abdéra
        ///Abdérita
        ///abdikácia/U
        ///abdikačný/YN
        ///abdikovaný/YN
        ///abdikovať/WN
        ///abdómen
        ///abdominálny/YN
        ///abdukcia
        ///Abeba/z
        ///abecedár
        ///abeceda/zZ
        ///abecedne
        ///abecedno
        ///abecedný/YN
        ///Ábel/C
        ///Ábelová
        ///Ábelovej
        ///Ábelovou
        ///Ábelovského
        ///Ábelovský
        ///Ábelovským
        ///aberácia
        ///Aberdeen
        ///Aberdeene
        ///aberdeenskym
        ///Abcházec/C
        ///Abcházka/zZ
        ///Abcházsko/M
        ///abcházsky/YN
        ///Abidžane
        ///Abidžanu
        ///abiogenéza [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sk_SK_dic {
            get {
                return ResourceManager.GetString("sk_SK_dic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///aby
        ///aj
        ///ako
        ///ale
        ///alebo
        ///ani
        ///asi
        ///až
        ///áno
        ///bez
        ///buď
        ///by
        ///cez
        ///či
        ///čo
        ///ešte
        ///ho
        ///i
        ///iba
        ///ich
        ///ja
        ///je
        ///jeho
        ///jej
        ///ju
        ///k
        ///ku
        ///kam
        ///kde
        ///keď
        ///kto
        ///menej
        ///mi
        ///moja
        ///moje
        ///môj
        ///my
        ///na
        ///nad
        ///nám
        ///než
        ///nič
        ///nie
        ///o
        ///od
        ///on
        ///ona
        ///oni
        ///ono
        ///po
        ///pod
        ///podľa
        ///pokiaľ
        ///potom
        ///práve
        ///prečo
        ///pred
        ///preto
        ///pretože
        ///pri
        ///s
        ///sa
        ///si
        ///sme
        ///so
        ///som
        ///späť
        ///ste
        ///sú
        ///ta
        ///tak
        ///takže
        ///tam
        ///tá
        ///táto
        ///teda
        ///ten
        ///tento
        ///tieto
        ///tiež
        ///to
        ///toho
        ///tom
        ///tomto
        ///toto
        ///tu
        ///túto
        ///ty
        ///tým
        ///týmto
        ///už
        ///v
        ///vám
        ///viac
        ///vo
        ///však
        ///vy
        ///z
        ///za
        ///zo.
        /// </summary>
        internal static string sk_SK_stopwords {
            get {
                return ResourceManager.GetString("sk_SK_stopwords", resourceCulture);
            }
        }
    }
}
